name: mlcourse
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.12.8
  - scipy
  - pytorch=2.5.1
  - matplotlib
  - numpy=2.2.2
  - ipykernel
  - pandas
  - openpyxl
  - scikit-learn
  - xarray
  - cartopy
  - netcdf4
  - tqdm
